name: CI for Linting Test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Begin ESLint Linting
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Use Cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key:  nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      
      - name: Install Dependencies
        run: yarn install
        
      - name: Run ESLint
        run: yarn lint
    
